spring.application.name=multitool-api

# Po??czenie z baz? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/multitooldb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

# Logowanie zapyta? SQL w konsoli
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ----------------------------
# Flyway Configuration
# ----------------------------

# Enables Flyway database migrations at application startup.
# Explicit for clarity, even though the Flyway starter enables it by default.
spring.flyway.enabled=true

# Location where Flyway looks for migration scripts.
# By convention: src/main/resources/db/migration
spring.flyway.locations=classpath:db/migration